on:
  push:
    branches:
      - master
    tags-ignore:
      - '*'
  pull_request:

jobs:
  build-windows:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: "actions/checkout@v2"
      - name: Install g++-mingw-w64
        run: |
          sudo apt update
          sudo apt install g++-mingw-w64
          sudo apt install build-essential libgtk-3-dev
      - name: Build tools
        run: |
          cd windows
          make GXX=x86_64-w64-mingw32-g++ WINDRES=x86_64-w64-mingw32-windres
          cd ../linux
          make
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: "actions/checkout@v2"
      - name: Build tools
        run: |
          cd swift
          make
